### ISSUE TITLE
git tag `v0.1.2` is missing

### ISSUE THREAD

**Issue by takuhiro** [quobyte/quobyte-csi-pod-killer#4]
`v0.1.2` is missing in the git repository now.
https://github.com/quobyte/quobyte-csi-pod-killer/tags

`v0.1.2` is used in the latest quobyte-csi (v1.8.2) and I can pull the docker image.
https://github.com/quobyte/quobyte-csi/blob/v1.8.2/quobyte-csi-driver/values.yaml#L70

```
% docker pull quay.io/quobyte/pod-killer:v0.1.2
v0.1.2: Pulling from quobyte/pod-killer
da7391352a9b: Pull complete 
14428a6d4bcd: Pull complete 
2c2d948710f2: Pull complete 
cf1780349c7b: Pull complete 
0fa9e2819140: Pull complete 
Digest: sha256:99e365424fbf2e662b9dc864d811df958d75142a3a85541630d87f05d8e57bb9
Status: Downloaded newer image for quay.io/quobyte/pod-killer:v0.1.2
quay.io/quobyte/pod-killer:v0.1.2
```

@venkatsc  Has the git tag been accidentally deleted?

**Comment by tksm** [comment]
It seems that the `v0.1.3` tag [pushed to quay.io](https://quay.io/repository/quobyte/pod-killer?tab=tags) is also missing.

**Comment by venkatsc** [comment]
Hi

@takuhiro @tksm
Added tags on repo as well. Looks like tagging is missed in the build script and we will add it so that we do not miss tags next time.

**Comment by takuhiro** [comment]
@venkatsc Thank you for the fix.
